name = "DataShieldOpal"
uuid = "c069a85d-6d2a-52a4-ad13-0e91be70ca39"
authors = ["Hugo Solleder <hugo.solleder@epfl.ch>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Opal = "81530b0b-e860-4d32-b636-0eb2a45cc020"

[compat]
DataFrames = "1.8.1"
Opal = "1"
julia = "1.10"
